### ISSUE TITLE
Dependabot updates to 47d60e3

### ISSUE THREAD

**Issue by bbodensieck** [cerbos/cerbos-sdk-java#49]
It seems that dependabot is taking the first entry as the newest. 
https://mvnrepository.com/artifact/dev.cerbos/cerbos-sdk-java
So it suggests `47d60e3` as an update.

It does not make a difference if the tag is like
```
implementation("dev.cerbos:cerbos-sdk-java:0.+")
```

or like

```
implementation("dev.cerbos:cerbos-sdk-java:0.7.0")
```

I would say getting rid of `47d60e3` would be a solution but I don't know if anyone is still using it.

To avoid the update issue I ignore the dependency in `dependabot.yml` for now like
```yaml
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "dev.cerbos:cerbos-sdk-java"
```
